### ISSUE TITLE
MrFakeGame Version 1.0.1 Checklist

### ISSUE THREAD

**Issue by fakerybakery** [fakerybakery/MrFakeGame#1]
This is the feature list for version 1.0.1

**Comment by fakerybakery** [comment]
- [ ] Add mobile phone support for the web
- [ ] Add mobile application (Cordova)
- [ ] Add Electron apps for macOS, Linux, and Windows

**Comment by fakerybakery** [comment]
Update: Next version coming soon! Looking forward to add mobile support for the web!

**Comment by fakerybakery** [comment]
Version 1.0.1 now has a dividing line. The red dot is on one side and the player's icon is on the other side.
